export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const FETCH_MOVIE_DETAILS_SUCCESS ='FETCH_MOVIE_DETAILS_SUCCESS'
 export const FETCH_MOVIE_DETAILS_FAILURE= 'FETCH_MOVIE_DETAILS_FAILURE'
 export const FETCH_SERIES_SUCCESS = 'FETCH_SERIESS_SUCCESS';
export const FETCH_SERIES_FAILURE = 'FETCH_SERIES_FAILURE';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
